In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train = pd.read_csv('Sample data.csv')

In [3]:
train.head()

,ip,date,time,zone,click,accession,extention,code,size,idx,norefer,noagent,find,crawler,browser
0,68.5.137.fad,30-06-2003,00:00:02,400,1089029,0001125282-03-003890,b325465_10qsb.txt,200,92131,0,0,0,9,0,mie
1,160.43.250.ach,30-06-2003,00:00:04,400,709519,0000891618-02-004480,f83969e10vk.htm,200,1369792,0,0,0,9,0,win
2,68.109.63.ijh,30-06-2003,00:00:05,400,1160294,0001047469-03-009734,#NAME?,200,6091,1,0,0,1,0,mie
3,64.229.80.fbb,30-06-2003,00:00:07,400,1241346,0001241346-03-000001,xslF345/primary_doc.xml,200,16243,0,0,0,10,0,win
4,65.89.171.iae,30-06-2003,00:00:07,400,773141,0001193964-03-000002,xslF345/form4_061203ex.xml,200,17460,0,1,0,0,0,NaN